http:
  port: 8080
admin:
  port: 9876
  hostname: localhost

apiEndpoints:
  api:
    host: '*'
    paths: '/ip'
  dummy:
    host: '*'
    paths: '/dummy'
  restless:
    host: '*'
    paths: '/restless/api'

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  dummy:
    url: 'http://localhost:5000'
  restless:
    url: 'http://restless:5001'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  dummy:
    apiEndpoints:
      - dummy
    policies:
      - proxy:
        - action:
            serviceEndpoint: dummy
            changeOrigin: true
            stripPath: true
  restless:
    apiEndpoints:
      - restless
    policies:
      - proxy:
        - action:
            serviceEndpoint: restless
            changeOrigin: true
            stripPath: true
