version: '3'

services:
  gateway:
    build: ./services/api-gateway
    command: npm start
    ports:
      - "8080:8080"
    networks:
      main:

  dummy:
    build: ./services/dummy-microservice
    # command: gunicorn main.wsgi --bind dummy:5000 -w 4
    command: gunicorn --bind=dummy:5000 -w 4 dummy:app
    networks:
      main:

networks:
  main: